apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-backend
  namespace: main
  labels:
    app: main-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-backend
  template:
    metadata:
      labels:
        app: main-backend
    spec:
      containers:
      - name: main-backend
        image: nald.me:5001/docker/main/backend:__DOCKER_IMG_VER__
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: main-backend
  namespace: main
spec:
  selector:
    app: main-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
