nald:
  token-expired-time: 2
  private-key: ${PRIVATE_KEY}
  public-key: ${PUBLIC_KEY}
  default-account-id: ${DEFAULT_ACCOUNT_ID}
  default-account-name: ${DEFAULT_ACCOUNT_NAME}
  default-account-password: ${DEFAULT_ACCOUNT_PASSWORD}
  contact-host: ${CONTACT_HOST}
  contact-email: ${CONTACT_EMAIL}
  contact-user: ${CONTACT_USER}
  contact-password: ${CONTACT_PASSWORD}
  common-path: /nfs
  ffmpeg-path: /usr/bin
  tomcat-temp-file-path: /tomcat/temp

server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: -1  # 파일 하나의 최대 크기  예; 10MB
      max-request-size: -1 # 한 번에 최대 업로드 가능 용량 예; 30MB
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      connection-test-query: SELECT 1
      maxLifeTime: 3300000
      connection-timeout: 30000
      idle-timeout: 600000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #swagger
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false # 콘솔에 sql문출력
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          use-new-id-generator-mappings: false
          default_batch_fetch_size: 1000
docker:
  endpoint: ${DOCKER_REPO_ENDPOINT}
  username: ${DOCKER_REPO_USERNAME}
  secret-password: ${DOCKER_REPO_SECRET_PASSWORD}
  password: ${DOCKER_REPO_PASSWORD}
  email: ${DOCKER_REPO_EMAIL}
  repository-uri: ${DOCKER_REPO_URI}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: error
    org.springframework.web: error
  config: classpath:logback-spring.xml




